monuments = [
    "Eiffel Tower",
    "Great Wall of China",
    "Taj Mahal",
    "Pyramids of Giza",
    "Statue of Liberty",
    "Machu Picchu",
    "Colosseum",
    "Stonehenge",
    "Christ the Redeemer",
    "Petra, Jordan",
    "Acropolis of Athens",
    "Chichen Itza",
    "Big Ben",
    "Angkor Wat",
    "Sagrada Família",
    "Venice Canals",
    "Alhambra",
    "Versailles Palace",
    "Pisa Tower",
    "Forbidden City",
    "Mount Rushmore",
    "St. Peter's Basilica",
    "Sydney Opera House",
    "Mount Everest",
    "The Louvre",
    "Golden Gate Bridge",
    "Angels Landing",
    "Santorini",
    "Mesa Verde",
    "Neuschwanstein Castle",
    "Mojave Desert",
    "Grand Canyon",
    "Red Square",
    "Victoria Falls",
    "Great Barrier Reef",
    "Parthenon",
    "Borobudur",
    "Easter Island Moai",
    "Saint Mark's Basilica",
    "Mount Fuji",
    "Yellowstone National Park",
    "Meteora",
    "St. Basils Cathedral",
    "Ayers Rock (Uluru)",
    "Stone Town, Zanzibar",
    "Hagia Sophia",
    "Mongolia Steppe",
    "Blue Lagoon, Iceland",
    "Machu Picchu",
    "Zion National Park",
    "Cappadocia",
    "Cinque Terre",
    "Trolltunga",
    "Bryce Canyon",
    "Antelope Canyon",
    "Mesa Arch",
    "St. Peter's Square",
    "Santorini",
    "Ngorongoro Crater",
    "Auschwitz",
    "Matterhorn",
    "Great Ocean Road",
    "Prague Castle",
    "Meteora",
    "Iguazu Falls",
    "Trolltunga",
    "Bryce Canyon",
    "Arches National Park",
    "Yellowstone National Park",
    "Mesa Verde",
    "Sistine Chapel",
    "St. Mark's Square",
    "Burj Khalifa",
    "Potala Palace",
    "Tivoli Gardens",
    "Dead Sea",
    "Lake Bled",
    "Dubrovnik City Walls",
    "Pamukkale",
    "Santorini",
    "Dubai Marina",
    "Cliffs of Moher",
    "Jaisalmer Fort",
    "Lake Titicaca",
    "Antelope Canyon",
    "Palace of Westminster",
    "Tower Bridge",
    "Wailing Wall",
    "Lake Baikal",
    "Victoria Falls",
    "Potala Palace",
    "Red Square",
    "Matterhorn",
    "Meteora",
    "Bagan Temples",
    "Dubai Mall",
    "Neuschwanstein Castle",
    "Parc Guell",
    "Horseshoe Bend",
    "Amalfi Coast",
    "Mont St. Michel",
    "Santorini",
    "Easter Island Moai",
    "Angels Landing",
    "Château de Chambord",
    "Park Güell",
    "Grand Palace, Bangkok",
]

# Monuments in Europe
european_monuments = [
    "Eiffel Tower",
    "The Colosseum",
    "Sagrada Familia",
    "Acropolis of Athens",
    "Stonehenge",
    "Brandenburg Gate",
    "The Louvre",
    "Charles Bridge",
    "Neuschwanstein Castle",
    "Pantheon",
    "Parthenon",
    "St. Peter's Basilica",
    "Prague Castle",
    "Trevi Fountain",
    "Edinburgh Castle",
    "Pisa Cathedral",
    "Mont Saint-Michel",
    "Alhambra",
    "Dubrovnik City Walls",
    "Matterhorn",
    "Krakow Old Town",
    "Buda Castle",
    "Versailles Palace",
    "St. Mark's Basilica",
    "Cologne Cathedral",
    "Bran Castle",
    "Zugspitze",
    "Leaning Tower of Pisa",
    "Saint-Malo Ramparts",
    "Belvedere Palace",
    "La Rambla",
    "Blue Mosque",
    "Ephesus",
    "Florence Cathedral",
    "Alcazar of Segovia",
    "Bucharest Palace of the Parliament",
    "Budapest Parliament Building",
    "York Minster",
    "Amsterdam Canal Ring",
    "San Gimignano",
    "Wawel Castle",
    "Hofburg Palace",
    "Rock of Gibraltar",
    "Guernica Tree",
    "Giant's Causeway",
    "Cliffs of Moher",
    "Red Square",
    "Westminster Abbey",
]

# Monuments in America
american_monuments = [
    "Statue of Liberty",
    "Golden Gate Bridge",
    "Mount Rushmore",
    "Chichen Itza",
    "Machu Picchu",
    "Niagara Falls",
    "Christ the Redeemer",
    "Grand Canyon",
    "Tikal",
    "Teotihuacan",
    "Moai Statues",
    "Angel Falls",
    "Panama Canal",
    "Havana Old Town",
    "Belize Barrier Reef",
    "Victoria Falls",
    "Amazon Rainforest",
    "Chaco Culture National Historical Park",
    "Yellowstone National Park",
    "Mesa Verde",
    "Galapagos Islands",
    "Tulum",
    "Antelope Canyon",
    "Iguazu Falls",
    "Salar de Uyuni",
    "Las Vegas Strip",
    "Amazon Theatre",
    "Torres del Paine",
    "Zion National Park",
    "Manchu Picchu",
    "Mesa Arch",
    "Denali National Park",
    "Cancun Underwater Museum",
    "Copper Canyon",
    "Monteverde Cloud Forest Reserve",
    "Death Valley National Park",
    "Bryce Canyon National Park",
    "Arches National Park",
    "Great Wall of China",
    "New Orleans French Quarter",
    "Monument Valley",
    "Horseshoe Bend",
    "Yellowstone Lake",
    "Kilauea Volcano",
    "Carlsbad Caverns National Park",
    "Cahokia Mounds",
    "Chalcatzingo",
]